<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>foldingStartMarker</key>
	<string>/\*\*</string>
	<key>foldingStopMarker</key>
	<string>\*/</string>
	<key>name</key>
	<string>AsDoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(/\*\*)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.asdoc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.asdoc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.asdoc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#left-margin</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*\w</string>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.comment.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)param)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.param.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.param.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)return)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.return.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.return.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)throws)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.throws.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.throws.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)see)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.see.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.see.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)author)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.author.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.author.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)version)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.version.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.version.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)see)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.see.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.see.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)since)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.since.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.since.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)inheritDoc)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.inheritDoc.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.inheritDoc.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)example)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.example.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.example.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)exampleText)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.exampleText.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.exampleText.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)eventType)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.eventType.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.eventType.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)internal)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.internal.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.internal.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)deprecated)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.deprecated.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.deprecated.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)playerversion)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.playerversion.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.playerversion.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\*\s*((\@)langversion)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.langversion.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*\*\s*@)|(?=\s*\*\s*/)</string>
					<key>name</key>
					<string>meta.documentation.tag.langversion.asdoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.custom.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\*\s*((\@)\w+)\s</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#left-margin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-formatting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man|gopher|txmt)://|mailto:)[-:@a-zA-Z0-9_.~%+/?=&amp;#]+(?&lt;![.?:])</string>
					<key>name</key>
					<string>markup.underline.link</string>
				</dict>
			</array>
		</dict>
		<key>inline-formatting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{)((\@)code)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.code.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.code.asdoc</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.code.asdoc</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)((\@)literal)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.literal.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.literal.asdoc</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.directive.literal.asdoc</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.docRoot.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)docRoot)(\})</string>
					<key>name</key>
					<string>meta.directive.docRoot.asdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.inheritDoc.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)inheritDoc)(\})</string>
					<key>name</key>
					<string>meta.directive.inheritDoc.asdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.link.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.asdoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.link-label.asdoc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)link)(?:\s+(\S+?))?(?:\s+(.+?))?\s*(\})</string>
					<key>name</key>
					<string>meta.directive.link.asdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.linkplain.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>markup.underline.linkplain.asdoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.linkplain-label.asdoc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)linkplain)(?:\s+(\S+?))?(?:\s+(.+?))?\s*(\})</string>
					<key>name</key>
					<string>meta.directive.linkplain.asdoc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.begin.asdoc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.documentation.directive.value.asdoc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.asdoc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.source-constant.asdoc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.directive.end.asdoc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{)((\@)value)\s*(\S+?)?\s*(\})</string>
					<key>name</key>
					<string>meta.directive.value.asdoc</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^(?!\s*\*).*$\n?</string>
					<key>name</key>
					<string>invalid.illegal.missing-asterisk.asdoc</string>
				</dict>
			</array>
		</dict>
		<key>left-margin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(?=\*)</string>
					<key>name</key>
					<string>comment.block.documentation.left-margin.asdoc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.asdoc</string>
	<key>uuid</key>
	<string>D53985FC-8AF9-4EF8-B1E8-9AA517BC72EF</string>
</dict>
</plist>
